<h1> Dora the explorer

In [1]:
%load_ext autoreload

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
pd.set_option('display.max_rows', 200)
pd.set_option('display.max_columns', None)

In [7]:
%autoreload
import sys
from pipeline_old_remove_consec import Pipeline as Pipin
pipe = Pipin()
%load_ext autoreload

Current working directory: /Users/matsalexander/Desktop/Forest Gump/mats/test_consectutive_count../
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
# all_data = pipe.get_combined_datasets(offset_years=True)
all_data = pipe.get_combined_data()

In [ ]:
df1_0 = pipe.get_data("A",)
df2_0 = pipe.get_data("B")
df3_0 = pipe.get_data("C")

In [ ]:
df1_0 = pipe.remove_consecutive_measurments(df1_0, 4, 24)
df2_0 = pipe.remove_consecutive_measurments(df2_0, 4, 24)
df3_0 = pipe.remove_consecutive_measurments(df3_0, 4, 24)
print(df1_0.shape, df2_0.shape, df3_0.shape)

(34085, 51) (32844, 51) (26095, 51)

In [ ]:
df1_0.head(10)

,absolute_humidity_2m:gm3,air_density_2m:kgm3,ceiling_height_agl:m,clear_sky_energy_1h:J,clear_sky_rad:W,cloud_base_agl:m,dew_or_rime:idx,dew_point_2m:K,diffuse_rad:W,diffuse_rad_1h:J,direct_rad:W,direct_rad_1h:J,effective_cloud_cover:p,elevation:m,fresh_snow_12h:cm,fresh_snow_1h:cm,fresh_snow_24h:cm,fresh_snow_3h:cm,fresh_snow_6h:cm,is_day:idx,is_in_shadow:idx,msl_pressure:hPa,precip_5min:mm,precip_type_5min:idx,pressure_100m:hPa,pressure_50m:hPa,prob_rime:p,rain_water:kgm2,relative_humidity_1000hPa:p,sfc_pressure:hPa,snow_density:kgm3,snow_depth:cm,snow_drift:idx,snow_melt_10min:mm,snow_water:kgm2,sun_azimuth:d,sun_elevation:d,super_cooled_liquid_water:kgm2,t_1000hPa:K,total_cloud_cover:p,visibility:m,wind_speed_10m:ms,wind_speed_u_10m:ms,wind_speed_v_10m:ms,wind_speed_w_1000hPa:ms,estimated,observed,day_of_year,hour,pv_measurement,consecutive_count
0,7.700,1.22825,1728.949951,0.000000e+00,0.000000,1728.949951,0.0,280.299988,0.000000,0.000000,0.000000,0.000000,99.074997,6.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,1006.299988,0.0,0.0,993.750000,999.775024,0.0,0.000,71.674995,1005.799988,NaN,0.0,0.0,0.0,0.175,348.036743,3.774250,0.0,286.225006,100.000000,40386.476562,3.600,3.575,0.500,0.0,0.0,1.0,153.0,22.0,0.00,1
1,7.700,1.22350,1689.824951,0.000000e+00,0.000000,1689.824951,0.0,280.299988,0.000000,0.000000,0.000000,0.000000,99.750000,6.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,1005.200012,0.0,0.0,992.674988,998.650024,0.0,0.025,68.000000,1004.650024,NaN,0.0,0.0,0.0,0.200,91.980751,4.357250,0.0,286.899994,100.000000,33770.648438,3.350,3.350,0.275,0.0,0.0,1.0,153.0,23.0,0.00,3
2,7.875,1.21975,1563.224976,0.000000e+00,0.000000,1563.224976,0.0,280.649994,0.000000,0.000000,0.000000,0.000000,100.000000,6.0,0.0,0.0,0.0,0.0,0.0,0.00,1.0,1004.525024,0.0,0.0,992.000000,997.974976,0.0,0.100,67.949997,1003.950012,NaN,0.0,0.0,0.0,0.400,14.934750,3.309500,0.0,286.950012,100.000000,13595.500000,3.050,2.950,0.750,0.0,0.0,1.0,154.0,0.0,0.00,3
3,8.425,1.21800,1283.425049,2.086500e+02,0.750000,1283.425049,0.0,281.674988,0.300000,526.775024,0.000000,0.000000,100.000000,6.0,0.0,0.0,0.0,0.0,0.0,0.25,1.0,1004.025024,0.0,0.0,991.500000,997.449951,0.0,0.125,73.875000,1003.449951,NaN,0.0,0.0,0.0,0.550,28.630251,0.822500,0.0,286.750000,100.000000,2321.850098,2.725,2.600,0.875,0.0,0.0,1.0,154.0,1.0,0.00,3
4,8.950,1.21800,1003.500000,3.246815e+04,23.100000,1003.500000,0.0,282.500000,11.975000,22068.949219,0.150000,282.975006,84.875000,6.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,1003.099976,0.0,0.0,990.550049,996.500000,0.0,0.100,79.925003,1002.500000,NaN,0.0,0.0,0.0,0.250,41.997501,3.051250,0.0,286.450012,99.224998,11634.799805,2.550,2.350,0.925,0.0,0.0,1.0,154.0,2.0,19.36,1
5,9.250,1.21650,809.375000,1.794991e+05,84.375000,809.375000,0.0,283.049988,45.125000,102788.046875,6.300000,11627.549805,65.025002,6.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,1002.349976,0.0,0.0,989.750000,995.700012,0.0,0.000,82.849998,1001.674988,NaN,0.0,0.0,0.0,0.100,55.041748,8.071000,0.0,286.475006,94.800003,29848.199219,2.300,2.200,0.800,0.0,0.0,1.0,154.0,3.0,251.02,1
6,9.525,1.21300,757.775024,4.781178e+05,186.649994,757.775024,0.0,283.524994,89.525002,242438.000000,43.724998,90073.375000,77.550003,6.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,1001.825012,0.0,0.0,989.250000,995.200012,0.0,0.000,82.275002,1001.174988,NaN,0.0,0.0,0.0,0.000,67.898003,13.956500,0.0,286.825012,95.099998,35980.148438,2.325,2.200,0.750,0.0,0.0,1.0,154.0,4.0,263.78,1
7,9.700,1.20750,705.650024,8.926679e+05,311.525024,705.650024,0.0,283.799988,139.000000,411381.906250,53.099998,174254.546875,85.050003,6.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,1001.200012,0.0,0.0,988.700012,994.599976,0.0,0.000,78.699997,1000.500000,NaN,0.0,0.0,0.0,0.000,80.821251,20.406250,0.0,287.325012,97.150002,37874.523438,2.225,2.000,0.950,0.0,0.0,1.0,154.0,5.0,522.72,1
8,9.550,1.20500,669.650024,1.357902e+06,442.750000,669.650024,0.0,283.600006,167.100006,550960.562500,33.825001,156473.156250,96.750000,6.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,1000.750000,0.0,0.0,988.275024,994.200012,0.0,0.050,75.099998,1000.150024,NaN,0.0,0.0,0.0,0.125,94.178497,27.096001,0.0,287.450012,99.199997,25470.250000,2.350,1.750,1.525,0.0,0.0,1.0,154.0,6.0,904.42,1
9,9.450,1.20500,662.224976,1.821739e+06,567.299988,662.224976,0.0,283.524994,217.699997,692633.125000,17.600000,92651.218750,100.000000,6.0,0.0,0.0,0.0,0.0,0.0,1.00,0.0,1000.849976,0.0,0.0,988.349976,994.250000,0.0,0.150,74.199997,1000.174988,NaN,0.0,0.0,0.0,0.425,108.438499,33.660751,0.0,287.325012,100.000000,2655.699951,2.700,1.175,2.425,0.0,0.0,1.0,154.0,7.0,1238.82,1

In [ ]:
# df0, df1 = pipe.remove_consecutive_measurments(all_data.copy(), 4,34, fuck = True)
# relevant_columns = ["consecutive_count", "pv_measurement"]
# print(df0.shape, df1.shape)

In [ ]:
# make a list of 

numbers = [0 if c % 2 == 0 else c for c in range(100)]
numbers = [0,0,0,0,0] + numbers +[0,0,0,0]

od = pd.DataFrame(numbers, columns=["pv_measurement"])
# od
conscs = pipe.remove_consecutive_measurments(od, 3, 12, fuck= True)
# conscs, coc = pipe.remove_consecutive_measurments(od, 3, 12, fuck= True)
conscs

     pv_measurement  consecutive_count
0                 0                  1
1                 0                  5
2                 0                  5
3                 0                  5
4                 0                  5
5                 0                  5
6                 1                  2
7                 0                  2
8                 3                  2
9                 0                  2
10                5                  2
11                0                  2
12                7                  2
13                0                  2
14                9                  2
15                0                  2
16               11                  2
17                0                  2
18               13                  2
19                0                  2
20               15                  2
21                0                  2
22               17                  2
23                0                  2
24               19                  2
25                0                  2
26               21                  2
27                0                  2
28               23                  2
29                0                  2
30               25                  2
31                0                  2
32               27                  2
33                0                  2
34               29                  2
35                0                  2
36               31                  2
37                0                  2
38               33                  2
39                0                  2
40               35                  2
41                0                  2
42               37                  2
43                0                  2
44               39                  2
45                0                  2
46               41                  2
47                0                  2
48               43                  2
49                0                  2
50               45                  2
51                0                  2
52               47                  2
53                0                  2
54               49                  2
55                0                  2
56               51                  2
57                0                  2
58               53                  2
59                0                  2
60               55                  2
61                0                  2
62               57                  2
63                0                  2
64               59                  2
65                0                  2
66               61                  2
67                0                  2
68               63                  2
69                0                  2
70               65                  2
71                0                  2
72               67                  2
73                0                  2
74               69                  2
75                0                  2
76               71                  2
77                0                  2
78               73                  2
79                0                  2
80               75                  2
81                0                  2
82               77                  2
83                0                  2
84               79                  2
85                0                  2
86               81                  2
87                0                  2
88               83                  2
89                0                  2
90               85                  2
91                0                  2
92               87                  2
93                0                  2
94               89                  2
95                0                  2
96               91                  2
97                0                  2
98               93                  2
99                0                  2
100              95                  2
101               0                  2
102              97                  2
103               0                  2
104              99                  2
105               0                  2
106               0                  3
107               0                  3
108               0                  3

In [12]:
%autoreload
import sys
# print system paths 
sys.path.append("../")
from pipeline import Pipeline as Pipin
pipe2 = Pipin()
%load_ext autoreload

/Users/matsalexander/Desktop/Forest Gump/mats/test_consectutive_count
/Users/matsalexander/.pyenv/versions/3.8.18/lib/python38.zip
/Users/matsalexander/.pyenv/versions/3.8.18/lib/python3.8
/Users/matsalexander/.pyenv/versions/3.8.18/lib/python3.8/lib-dynload

/Users/matsalexander/.pyenv/versions/3.8.18/envs/pycaret/lib/python3.8/site-packages
../
../
Current working directory: /Users/matsalexander/Desktop/Forest Gump/mats/test_consectutive_count
The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [ ]:
numbers = [0 if c % 2 == 0 else c for c in range(100)]
numbers = [0,0,0,0,0] + numbers +[0,0,0,0]

od = pd.DataFrame(numbers, columns=["pv_measurement"])
# od
conscs = pipe2.remove_consecutive_measurments_new(od, 3, 12, retrun_counted=True)
# conscs, coc = pipe.remove_consecutive_measurments(od, 3, 12, fuck= True)
conscs

     pv_measurement  consecutive_group  is_first_in_consecutive_group
0                 0                  6                           True
1                 0                  6                          False
2                 0                  6                          False
3                 0                  6                          False
4                 0                  6                          False
5                 0                  6                          False
6                 1                  1                           True
7                 0                  1                          False
8                 3                  1                          False
9                 0                  1                          False
10                5                  1                          False
11                0                  1                          False
12                7                  1                          False
13                0                  1                          False
14                9                  1                          False
15                0                  1                          False
16               11                  1                          False
17                0                  1                          False
18               13                  1                          False
19                0                  1                          False
20               15                  1                          False
21                0                  1                          False
22               17                  1                          False
23                0                  1                          False
24               19                  1                          False
25                0                  1                          False
26               21                  1                          False
27                0                  1                          False
28               23                  1                          False
29                0                  1                          False
30               25                  1                          False
31                0                  1                          False
32               27                  1                          False
33                0                  1                          False
34               29                  1                          False
35                0                  1                          False
36               31                  1                          False
37                0                  1                          False
38               33                  1                          False
39                0                  1                          False
40               35                  1                          False
41                0                  1                          False
42               37                  1                          False
43                0                  1                          False
44               39                  1                          False
45                0                  1                          False
46               41                  1                          False
47                0                  1                          False
48               43                  1                          False
49                0                  1                          False
50               45                  1                          False
51                0                  1                          False
52               47                  1                          False
53                0                  1                          False
54               49                  1                          False
55                0                  1                          False
56               51                  1                          False
57                0                  1                          False
58               53                  1                          False
59                0                  1                          False
60               55                  1                          False
61                0                  1                          False
62               57                  1                          False
63                0                  1                          False
64               59                  1                          False
65                0                  1                          False
66               61                  1                          False
67                0                  1                          False
68               63                  1                          False
69                0                  1                          False
70               65                  1                          False
71                0                  1                          False
72               67                  1                          False
73                0                  1                          False
74               69                  1                          False
75                0                  1                          False
76               71                  1                          False
77                0                  1                          False
78               73                  1                          False
79                0                  1                          False
80               75                  1                          False
81                0                  1                          False
82               77                  1                          False
83                0                  1                          False
84               79                  1                          False
85                0                  1                          False
86               81                  1                          False
87                0                  1                          False
88               83                  1                          False
89                0                  1                          False
90               85                  1                          False
91                0                  1                          False
92               87                  1                          False
93                0                  1                          False
94               89                  1                          False
95                0                  1                          False
96               91                  1                          False
97                0                  1                          False
98               93                  1                          False
99                0                  1                          False
100              95                  1                          False
101               0                  1                          False
102              97                  1                          False
103               0                  1                          False
104              99                  1                          False
105               0                  4                           True
106               0                  4                          False
107               0                  4                          False
108               0                  4                          False